# Basic Information 
title: Yiwei Wang
position: Applied Scientist
affiliation: Amazon Inc.
affiliation_link: https://www.amazon.science/
email: wangyw_seu (at) foxmail.com

# Search Engine Optimization (SEO)
keywords: yiwei wang, wang yiwei, nus, amazon
canonical: https://www.cs.jhu.edu/~yyliu/
description: Yiwei Wang is an Applied Scientist at Amazon Inc. His research lies in natural language processing and graph neural networks.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: true

# Links
google_scholar: https://scholar.google.com/citations?user=Uf9GqRsAAAAJ
cv_link: https://files.yliu.me/Yaoyao_Liu_Curriculum_Vitae.pdf
github_link: https://github.com/yaoyao-liu/
linkedin: https://www.linkedin.com/in/liuyaoyao/
twitter: https://twitter.com/YaoyaoLiu1/

# Images 
avatar: ./photo.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
